### ISSUE TITLE
Can I use it for core(basic) PHP developed website?

### ISSUE THREAD

**Issue by yudhir** [sudiptpa/esewa#5]
I am going to develop a core php with as simple setup as you can imagine based on my limited knowledge . Just simple cart for few products and checkout with Esewa. What are your experiences regarding this and About Omnipay , this sounds good!!

**Comment by sudiptpa** [comment]
Hey @yudhir 

Yes ! off course you can use it without frameworks, it is designed to use with all types of projects.
If you have experience with composer it will much easier to you.

I am sorry to inform you that currently the package is still in development phase. It has no any tag releases yet !

Works are crazy these days so i am not getting time to go ahead with the development.

Also i have good experience with Omnipay Payment processing library, i have contributed on few Omnipay based payment packages in Github. 

If you are curious, please have a look at my packages which are in production at the moment.

https://github.com/sudiptpa/omnipay-nabtransact
https://github.com/sudiptpa/paypal-ipn

If you have time to contribute to this esewa package please feel free to create a PR.


Thanks !

**Comment by yudhir** [comment]
Thanks fo reply , I will look into those and Esewa Integration too .
Is this library a good way to move forward , Have you tested them on your projects ? I think I can learn some framework like ,  Slim or Silex to develop the web app , REST apis etc as well. Do you have any other suggestion for this particular usecase  too?

**Comment by sudiptpa** [comment]
I really think re-usability and maintainability before working on projects, so i intended to build this package as a open source so that many people can use it and maintain it for all.
 
I mostly use Laravel framework to build web apps, APIs, also look at Lumen a micro framework introduced by Laravel. I really love laravel syntax, much fluent and laravel is much popular these days.

**Comment by sudiptpa** [comment]
The packages i have built  are fully unit tested, those released packages are stable release and few of my projects are using them on production.
